/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as XbotRouteImport } from './routes/xbot'
import { Route as CratesIndexRouteImport } from './routes/crates.index'
import { Route as CratesCrateRouteImport } from './routes/crates.$crate'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const XbotRoute = XbotRouteImport.update({
  id: '/xbot',
  path: '/xbot',
  getParentRoute: () => rootRouteImport,
} as any)
const CratesIndexRoute = CratesIndexRouteImport.update({
  id: '/crates/',
  path: '/crates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CratesCrateRoute = CratesCrateRouteImport.update({
  id: '/crates/$crate',
  path: '/crates/$crate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/community': typeof CommunityRoute
  '/docs': typeof DocsRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/examples': typeof ExamplesRoute
  '/patterns': typeof PatternsRoute
  '/roadmap': typeof RoadmapRoute
  '/xbot': typeof XbotRoute
  '/crates/$crate': typeof CratesCrateRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/crates/': typeof CratesIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/community': typeof CommunityRoute
  '/ecosystem': typeof EcosystemRoute
  '/examples': typeof ExamplesRoute
  '/patterns': typeof PatternsRoute
  '/roadmap': typeof RoadmapRoute
  '/xbot': typeof XbotRoute
  '/crates/$crate': typeof CratesCrateRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/crates': typeof CratesIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/community': typeof CommunityRoute
  '/docs': typeof DocsRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/examples': typeof ExamplesRoute
  '/patterns': typeof PatternsRoute
  '/roadmap': typeof RoadmapRoute
  '/xbot': typeof XbotRoute
  '/crates/$crate': typeof CratesCrateRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/crates/': typeof CratesIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/community'
    | '/docs'
    | '/ecosystem'
    | '/examples'
    | '/patterns'
    | '/roadmap'
    | '/xbot'
    | '/crates/$crate'
    | '/docs/getting-started'
    | '/crates/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/community'
    | '/ecosystem'
    | '/examples'
    | '/patterns'
    | '/roadmap'
    | '/xbot'
    | '/crates/$crate'
    | '/docs/getting-started'
    | '/crates'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/community'
    | '/docs'
    | '/ecosystem'
    | '/examples'
    | '/patterns'
    | '/roadmap'
    | '/xbot'
    | '/crates/$crate'
    | '/docs/getting-started'
    | '/crates/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CommunityRoute: typeof CommunityRoute
  DocsRoute: typeof DocsRouteWithChildren
  EcosystemRoute: typeof EcosystemRoute
  ExamplesRoute: typeof ExamplesRoute
  PatternsRoute: typeof PatternsRoute
  RoadmapRoute: typeof RoadmapRoute
  XbotRoute: typeof XbotRoute
  CratesCrateRoute: typeof CratesCrateRoute
  CratesIndexRoute: typeof CratesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xbot': {
      id: '/xbot'
      path: '/xbot'
      fullPath: '/xbot'
      preLoaderRoute: typeof XbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crates/': {
      id: '/crates/'
      path: '/crates'
      fullPath: '/crates/'
      preLoaderRoute: typeof CratesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crates/$crate': {
      id: '/crates/$crate'
      path: '/crates/$crate'
      fullPath: '/crates/$crate'
      preLoaderRoute: typeof CratesCrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  CommunityRoute: CommunityRoute,
  DocsRoute: DocsRouteWithChildren,
  EcosystemRoute: EcosystemRoute,
  ExamplesRoute: ExamplesRoute,
  PatternsRoute: PatternsRoute,
  RoadmapRoute: RoadmapRoute,
  XbotRoute: XbotRoute,
  CratesCrateRoute: CratesCrateRoute,
  CratesIndexRoute: CratesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
